### ISSUE TITLE
#23 MemberService signup Method isAgreed 확인 부탁 드립니다.

### ISSUE THREAD

**Issue by been1118** [hh99-14-Team3/BE_final#26]
#23 SignupRequestDto에 선언된 isAgreed가 없는데 signup Method에는 있는 것으로 확인됩니다.
isAgreed를 컬럼에서 지우기로 했는데 요청을 받을 때 동의 여부도 같이 받아야 할지 한 번 얘기해봐야 할 것 같습니다.
일단 signup Method에 선언된 isAgreed는 주석해놓겠습니다.

**Comment by been1118** [comment]
3eb3c7d

**Comment by been1118** [comment]
3eb3c7d 커밋 기록입니다.

**Comment by been1118** [comment]
작업하시기 전에 pull먼저 받고 작업해주세요. 
패키지 구조를 정리해 놓았습니다.
작업해 놓으신게 있다면 stash를 써서 충돌이 나지 않게 주의해주세요.

**Comment by mansooonuna** [comment]
체크 후 커밋완료
