### ISSUE TITLE
Friendship domain code review

### ISSUE THREAD

**Issue by been1118** [hh99-14-Team3/BE_final#87]
프론트 요청으로 friendship domain code 수정하다가 궁금한 점이 있습니다. 주석으로 궁금한 것들 적어놓았으니 커밋 내용 주석 확인 부탁드립니다.

**Comment by bheejun** [comment]
혹시 주석이 어디있는지 알 수 있을까요 못찾겠어요

**Comment by bheejun** [comment]
/**
         * 친구 요청 로직에서 이 밑부분까지 예외처리가 필요한지 궁금합니다.
         * 친구 요청을 보낼 때 이미 보내려고 하는 사람에게서 요청이 와있거나 거절했을 경우에 저렇게 리턴하면 한번 거절하면 영원히 친구를 못하게 되는건지,
         * 이미 요청이 와있을때에는 요청을 보내면 안되는 이유가 있는 건지 궁금합니다.
         */
         
         
1. 보통 친구 요청을 myPage 외부에서 하게 될 텐데(ex- 상대방 프로필 페이지에서 요청을 한다던가) 그렇다면 현재 친구 신청의 상태가 어떤지 자세히 알려줄 필요가 있다고 생각해서 예외 처리를 해뒀습니다. 그런게 필요 없다고 느껴지면 지워도 무방할 듯 합니다. 
2. 현재는 거절하면 다시 친구 못합니다. 원래는 이 거절 상태를 하루 지나면 삭제하려고 했는데 아직 구현 못했습니다. 
3. 이미 요청이 와있을 경우 다시 요청을 못하는 경우(ex- a가 b에게 친구 신청을 했는데, b가 a에게 신청을 하는 상황)
이건 데이터의 중복을 막으려고 이렇게 했습니다. 그리고 동시에 두 방향의 요청을 허용하는 서비스를 본 적이 없어서 그랬습니다.
